// Own observation of unchanged native enchantment constructors, stream fields and equals.
import com.google.gson.*;import io.netty.buffer.ByteBuf;import io.netty.buffer.Unpooled;import java.nio.file.*;import java.lang.reflect.*;import java.util.*;import java.io.*;
public class ExportEnchantmentConstructors {
 static byte[] encode(Object codec,Object value)throws Exception {ByteBuf bytes=Unpooled.buffer();try{ExportItemComponents.codecClass.getMethod("encode",Object.class,Object.class).invoke(codec,ExportItemComponents.buffer(bytes),value);byte[] out=new byte[bytes.readableBytes()];bytes.getBytes(0,out);return out;}finally{bytes.release();}}
 static Object keyCodec(Object codec)throws Exception {Object map=ExportItemComponentSchema.field(codec,"a");for(Field f:map.getClass().getDeclaredFields())if(!Modifier.isStatic(f.getModifiers())){f.setAccessible(true);Object v=f.get(map);if(v!=null&&v.getClass().getName().equals("aam$22"))return v;}throw new IllegalStateException("original enchantment key codec missing");}
 static JsonArray fields(Object value,Object key)throws Exception {Map<?,?> map=(Map<?,?>)ExportItemComponentSchema.field(value,"e");TreeMap<String,Integer> ordered=new TreeMap<>();for(var entry:map.entrySet())ordered.put(HexFormat.of().formatHex(encode(key,entry.getKey())),(Integer)entry.getValue());JsonArray out=new JsonArray();for(var e:ordered.entrySet()){JsonObject v=new JsonObject();v.addProperty("key_hex",e.getKey());v.addProperty("level",e.getValue());out.add(v);}return out;}
 public static void main(String[] args)throws Exception {
  Path base=Path.of(args[1]).getParent();try(PrintWriter out=new PrintWriter(Files.newBufferedWriter(base.resolve("original-enchantments-bytecode.log")))){int status=java.util.spi.ToolProvider.findFirst("javap").orElseThrow().run(out,out,"-classpath",System.getProperty("java.class.path"),"-p","-c","dsu","aam$18","aam$22");if(status!=0)throw new IllegalStateException("original enchantments inspection failed");}
  ExportItemProperties.init("1.21.11");Map<String,Object> codecs=new HashMap<>();for(Object c:(Iterable<?>)ExportItemProperties.components){String name=ExportItemProperties.name.invoke(ExportItemProperties.components,c).toString();if(name.equals("minecraft:enchantments")||name.equals("minecraft:stored_enchantments"))codecs.put(name,Class.forName("kh").getMethod("f").invoke(c));}
  JsonArray cases=new JsonArray(),pairs=new JsonArray();List<Object> values=new ArrayList<>();
  for(JsonElement e:JsonParser.parseString(Files.readString(Path.of(args[0]))).getAsJsonArray()){JsonObject r=e.getAsJsonObject().deepCopy();Object codec=codecs.get(r.get("component").getAsString());if(codec==null)throw new IllegalStateException("own unknown component request");Object v;
   try{v=ExportComponentValueRules.decode(codec,HexFormat.of().parseHex(r.get("input_hex").getAsString()));}catch(InvocationTargetException|IllegalStateException error){Throwable t=ExportComponentNormalization.cause(error);if(t instanceof Error fatal)throw fatal;r.addProperty("accepted",false);r.addProperty("failure",t.getClass().getName()+": "+t.getMessage());cases.add(r);values.add(null);continue;}
   r.addProperty("accepted",true);r.add("fields",fields(v,keyCodec(codec)));r.addProperty("encoded_hex",HexFormat.of().formatHex(encode(codec,v)));cases.add(r);values.add(v);
  }
  for(int a=0;a<values.size();a++)for(int c=a;c<values.size();c++)if(values.get(a)!=null&&values.get(c)!=null){JsonObject p=new JsonObject();p.addProperty("a",a);p.addProperty("b",c);p.addProperty("equal",values.get(a).equals(values.get(c)));pairs.add(p);}
  JsonObject out=new JsonObject();out.add("cases",cases);out.add("pairs",pairs);out.addProperty("java_version",System.getProperty("java.version"));Files.writeString(Path.of(args[1]),new GsonBuilder().serializeNulls().create().toJson(out));Class.forName("bas").getMethod("close").invoke(ExportItemComponents.resourceManager);System.out.println("original enchantment cases="+cases.size()+" pairs="+pairs.size());
 }
}
