// Own observer of unchanged nested item stream constructors/prototype/weight fields and equals.
import com.google.gson.*;import java.nio.file.*;import java.lang.reflect.*;import java.util.*;import java.io.*;
public class ExportNestedItemConstructors {
 static JsonObject item(Object value)throws Exception {JsonObject out=new JsonObject();out.addProperty("count",(Integer)ExportItemProperties.stack.getMethod("N").invoke(value));out.add("properties",ExportItemProperties.properties(value));out.addProperty("empty",(Boolean)ExportItemProperties.stack.getMethod("f").invoke(value));out.addProperty("encoded_hex",HexFormat.of().formatHex(ExportEnchantmentConstructors.encode(ExportItemProperties.stack.getField("h").get(null),value)));return out;}
 static JsonObject fields(String name,Object value)throws Exception {JsonObject out=new JsonObject();List<?> items;if(name.equals("minecraft:use_remainder"))items=List.of(ExportItemComponentSchema.field(value,"c"));else items=(List<?>)ExportItemComponentSchema.field(value,name.equals("minecraft:container")?"f":name.equals("minecraft:bundle_contents")?"g":"d");JsonArray nested=new JsonArray();for(Object v:items)nested.add(item(v));out.add("items",nested);if(name.equals("minecraft:bundle_contents")){org.apache.commons.lang3.math.Fraction weight=(org.apache.commons.lang3.math.Fraction)ExportItemComponentSchema.field(value,"h");out.addProperty("weight",weight.toString());out.addProperty("numerator",weight.getNumerator());out.addProperty("denominator",weight.getDenominator());out.addProperty("selected",(Integer)ExportItemComponentSchema.field(value,"i"));}return out;}
 public static void main(String[] args)throws Exception {
  Path base=Path.of(args[1]).getParent();try(PrintWriter log=new PrintWriter(Files.newBufferedWriter(base.resolve("original-nested-items-bytecode.log")))){int status=java.util.spi.ToolProvider.findFirst("javap").orElseThrow().run(log,log,"-classpath",System.getProperty("java.class.path"),"-p","-c","doo","dnz","doa","dpi","dlt$1","dlt$2");if(status!=0)throw new IllegalStateException("original nested item inspection failed");}
  ExportItemProperties.init("1.21.11");Map<String,Object> codecs=new HashMap<>();for(Object c:(Iterable<?>)ExportItemProperties.components){String name=ExportItemProperties.name.invoke(ExportItemProperties.components,c).toString();if(Set.of("minecraft:container","minecraft:bundle_contents","minecraft:charged_projectiles","minecraft:use_remainder").contains(name))codecs.put(name,Class.forName("kh").getMethod("f").invoke(c));}
  JsonArray rows=new JsonArray(),pairs=new JsonArray();List<Object> values=new ArrayList<>();for(JsonElement e:JsonParser.parseString(Files.readString(Path.of(args[0]))).getAsJsonArray()){JsonObject row=e.getAsJsonObject().deepCopy();String name=row.get("component").getAsString();Object codec=codecs.get(name),v;if(codec==null)throw new IllegalStateException("own unknown nested component request");try{v=ExportComponentValueRules.decode(codec,HexFormat.of().parseHex(row.get("input_hex").getAsString()));}catch(InvocationTargetException|IllegalStateException error){Throwable t=ExportComponentNormalization.cause(error);if(t instanceof Error fatal)throw fatal;row.addProperty("accepted",false);row.addProperty("failure",t.getClass().getName()+": "+t.getMessage());rows.add(row);values.add(null);continue;}row.addProperty("accepted",true);row.add("fields",fields(name,v));row.addProperty("encoded_hex",HexFormat.of().formatHex(ExportEnchantmentConstructors.encode(codec,v)));rows.add(row);values.add(v);}
  for(int a=0;a<values.size();a++)for(int b=a;b<values.size();b++)if(values.get(a)!=null&&values.get(b)!=null){JsonObject p=new JsonObject();p.addProperty("a",a);p.addProperty("b",b);p.addProperty("equal",values.get(a).equals(values.get(b)));pairs.add(p);}JsonObject out=new JsonObject();out.add("cases",rows);out.add("pairs",pairs);out.addProperty("java_version",System.getProperty("java.version"));Files.writeString(Path.of(args[1]),new GsonBuilder().serializeNulls().create().toJson(out));Class.forName("bas").getMethod("close").invoke(ExportItemComponents.resourceManager);System.out.println("native nested item rows="+rows.size()+" pairs="+pairs.size());
 }
}
