#!/usr/bin/env python3
"""Generate per-version Rust constant tables from bundled data.

Run from the repository root:  python3 scripts/generate_version_tables.py
Outputs are committed; `cargo test` checks that they still match their sources.
"""
import hashlib
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent


def rust_f64(value):
    text = repr(float(value))
    return text if "." in text or "e" in text else text + ".0"


def option(value, render):
    return "None" if value is None else f"Some({render(value)})"


def write_block_physics(path, source):
    digest = hashlib.sha256((ROOT / source).read_bytes()).hexdigest()
    blocks = json.loads((ROOT / source).read_text())["blocks"]
    lines = [
        "",
        f"// Source: {source} (sha256 {digest})",
        "/// Blocks whose friction, speed or jump factor differs from the default, sorted by name.",
        "pub(crate) static BLOCK_PHYSICS: &[BlockPhysics] = &[",
    ]
    for name in sorted(blocks):
        b = blocks[name]
        if (b["friction"], b["speed_factor"], b["jump_factor"]) == (0.6, 1.0, 1.0):
            continue
        lines.append(
            "    BlockPhysics { "
            f"name: {json.dumps(name)}, friction: {rust_f64(b['friction'])}, "
            f"speed_factor: {rust_f64(b['speed_factor'])}, jump_factor: {rust_f64(b['jump_factor'])} }},"
        )
    lines.append("];")
    with open(ROOT / path, "a") as out:
        out.write("\n".join(lines) + "\n")


def write(path, source, rows):
    digest = hashlib.sha256((ROOT / source).read_bytes()).hexdigest()
    lines = [
        "// @generated by scripts/generate_version_tables.py; do not edit.",
        f"// Source: {source} (sha256 {digest})",
        "use crate::versions::table::{BlockPhysics, EntityDimensions};",
        "",
        "/// Default entity dimensions sorted by name.",
        "pub(crate) static ENTITY_DIMENSIONS: &[EntityDimensions] = &[",
    ]
    for row in sorted(rows, key=lambda r: r["name"]):
        lines.append(
            "    EntityDimensions { "
            f"name: {json.dumps(row['name'])}, "
            f"width: {rust_f64(row['width'])}, "
            f"height: {rust_f64(row['height'])}, "
            f"eye_height: {option(row.get('eye_height'), rust_f64)}, "
            f"living: {option(row.get('living'), lambda v: 'true' if v else 'false')} }},"
        )
    lines.append("];")
    (ROOT / path).write_text("\n".join(lines) + "\n")


legacy = json.loads((ROOT / "data/entities.json").read_text())
write(
    "src/versions/java_1_16_1/generated.rs",
    "data/entities.json",
    [{"name": f"minecraft:{e['name']}", "width": e["width"], "height": e["height"]} for e in legacy],
)
modern = json.loads((ROOT / "data/java_1_21_11/entity_dimensions.json").read_text())["entities"]
write(
    "src/versions/java_1_21_11/generated.rs",
    "data/java_1_21_11/entity_dimensions.json",
    [{"name": name, **values} for name, values in modern.items()],
)
write_block_physics("src/versions/java_1_16_1/generated.rs", "data/client_api/block_physics-1.16.1.json")
write_block_physics("src/versions/java_1_21_11/generated.rs", "data/client_api/block_physics-1.21.11.json")
