allow-flight=false
difficulty=peaceful
enable-command-block=false
enable-query=false
enable-rcon=false
force-gamemode=true
gamemode=survival
generate-structures=true
hardcore=false
level-name=world
level-seed=81276491
level-type=default
max-players=20
motd=Voxrig interactive natural terrain
online-mode=false
player-idle-timeout=0
server-ip=127.0.0.1
server-port=25565
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
view-distance=8
white-list=false
