allow-flight=false
difficulty=peaceful
enable-command-block=false
enable-query=false
enable-rcon=false
force-gamemode=true
gamemode=survival
generate-structures=true
hardcore=false
level-name=world
level-seed=81276491
level-type=default
max-players=60
motd=Voxrig natural terrain test
online-mode=false
player-idle-timeout=0
server-port=25567
server-ip=127.0.0.1
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
view-distance=6
white-list=false
